version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore -verbosity detailed
build:
  verbosity: minimal
artifacts:
- path: '\src\Nancy.Self-Host.Template\bin\Release\'
  name: nancy-self-host
